platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

environment:
  RUN_IN_BAND: true

install:
  - ps: Install-Product node 6 x64
  # unknown yarn error
  - npm install
  - npm prune

build: off

test_script:
  - npm run test